patch: add `statusCode` to mocktr181's response payload
xmidt-org/xmidt-agent pull request #182
Opened 2024-07-08 17:17 UTC by denopink

- add the missing `statusCode` field to mocktr181's response payload

2024-07-08 17:17 UTC, denopink commented on internal/wrphandlers/mocktr181/handler.go
> -
this is out of order, should be set before payload marshaling

2024-07-10 20:24 UTC, denopink commented on internal/wrphandlers/mocktr181/handler.go
> +					Count:      1,
note: non-wildcard `get`s will always have a Count of 1 (based on `parodus2ccsp` and `wdmp-c`)

2024-07-10 21:14 UTC, schmidtw requested changes

2024-07-10 21:14 UTC, schmidtw commented on internal/wrphandlers/mocktr181/handler.go
> +	if len(result.Parameters) == 0 {
If you default the `StatusCode` to `520` and only set it when appending to the parameters on line 171, then no conditional check is needed here.

2024-07-11 04:11 UTC, schmidtw approved these changes

2024-07-11 04:11 UTC, merged